#Esta instruccion permite comunicarle a spring que en las propiedades de spring dev tools siempre excluya el path
#Esto con el objetivo de que no las recompile cada vez que se actualiza la aplicacion
restart.exclude.uploads=uploads/products/*