#Se usa .yml para que tenga una forma de arbol y se usa mucho en entornos empresariales
spring:
  application:
    name: expert

  #Se utiliza para poder activar ciertos perfiles de properties para spring
  profiles:
    #Se pueden pasar variables de entorno y configurarlas (DESDE DOCKER)
    #Esto permite poder especificar variables de entorno que pueden manejarse desde docker porque el solito las inserta
    #${VARIABLE_ENTORNO:valorPorDefecto}
    active: ${SPRING_PROFILES_ACTIVE:dev}