#Se usa ESTA CONFIGURACION EN ENTORNO DE DESARROLLO
#Se usa .yml para que tenga una forma de arbol y se usa mucho en entornos empresariales
spring:

  #Se pueden definir variables que se pueden utilizar como variables de entorno para poderlas usar en la aplicacion
  jwt:
    #Nombre de la variable
    secret: ${SECRET}
    #expiration: 86400000
    expiration: ${JWT_EXPIRATION}
    refresh-window: ${JWT_REFRESH_WINDOW}
  #se configuran los puertos en los que va a estar la base de datos y credenciales
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #Permite ver las querys sql que se han ejecutado en la base de datos
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      #Longitud de datos que acpeta como request el servidor (PREDETERMINADO)
      max-request-size: 20MB
      #Longitud de archivos manejados (PREDETERMINADO)
      max-file-size: 10MB
  cache:
    #Se especifica donde se va a chachear la informacion (SIMPLE NO ES UTILIZADO SOLO ES A FINES PRACTICOS)
    #La mas utilizada normalmente es REDIS
    #LA APLICACION DE SPRING NO DEBE ALMACENAR MEMORIA. POR ESO SE CACHEA EXTERNAMENTE CON Redis
    type: simple

  #SE PUEDE ESPECIFICAR UNA ALIMENTACION A LA BASE DE DATOS (SEEDS)
  #PERO NO ES UTILIZADA MAYORMENTE PORQUE CAUSA EXCEPCIONES SI YA ESTAN INSERTADAS Y SIEMPRE INTENTA INSERTAR DE NUEVO LOS DATOS
  #CADA QUE ARRANCA LA APLICACION
  #  sql:
  #    init:
  #      mode: always
  #      data-locations: classpath:data.sql
  #Se especifica como se va a llamar la pagina html de swagger para poder ver la documentacion de la api
  springdoc:
    #PERMITE CONFIGURAR EL NOMBRE D ELA PAGINA EN LA PAGINA EN LA QUE SE VA A DOCUMENTAR
    swagger-ui:
      path: /swagger-ui.html
  
  #Propiedades extra para poder visualizar mejor la salud de la aplicacion
management:
  #Se pueden especificar metricas para el comportamiento de la aplicacion
  #Se pueden utilizar otros sistemas como grafana o prometeus para poder tener una mejor visualizacion
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http-server:
          requests: true

